// the goal of this project is to reverse engineer the binary file format of the after effects ffx format in ./test-files/pseudo.ffx and create a typescript library to read and write ffx files
// the ffx file generated by this should be output to ./output/pseudo.ffx

import * as fs from "fs";
import * as path from "path";

class FFXAnalyzer {
  private buffer: Buffer;

  constructor(filePath: string) {
    // Resolve path relative to dist directory
    const resolvedPath = path.resolve(__dirname, "../files", filePath);
    this.buffer = fs.readFileSync(resolvedPath);
  }

  analyze(): void {
    console.log("File size:", this.buffer.length, "bytes");

    // Print first 32 bytes as hex for header analysis
    console.log("\nHeader (first 32 bytes):");
    console.log(
      this.buffer.slice(0, 32).toString("hex").match(/.{2}/g)?.join(" ")
    );

    // Try to detect string patterns
    this.findStrings();

    // Look for common structural patterns
    this.analyzeStructure();
  }

  private findStrings(): void {
    let currentString = "";
    console.log("\nPossible string contents:");

    for (let i = 0; i < this.buffer.length; i++) {
      const byte = this.buffer[i];
      if (byte >= 32 && byte <= 126) {
        // Printable ASCII range
        currentString += String.fromCharCode(byte);
      } else if (currentString.length > 3) {
        // Only show strings longer than 3 chars
        console.log(`Offset ${i - currentString.length}: "${currentString}"`);
        currentString = "";
      } else {
        currentString = "";
      }
    }
  }

  private analyzeStructure(): void {
    // Look for repeated patterns or known markers
    console.log("\nStructural analysis:");

    // Common markers to look for
    const markers = [
      Buffer.from([0xff, 0xfe]), // UTF-16LE BOM
      Buffer.from([0xef, 0xbb, 0xbf]), // UTF-8 BOM
      Buffer.from("RIFX"), // Common AE format marker
    ];

    markers.forEach((marker) => {
      let offset = 0;
      while ((offset = this.buffer.indexOf(marker, offset)) !== -1) {
        console.log(`Found marker "${marker.toString()}" at offset: ${offset}`);
        offset += marker.length;
      }
    });
  }
}

// Usage
const analyzer = new FFXAnalyzer("test-files/pseudo.ffx");
analyzer.analyze();
